{{- if .Values.apiserver.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "batch-gateway.apiserver.fullname" . }}-config
  labels:
    {{- include "batch-gateway.apiserver.labels" . | nindent 4 }}
data:
  config.yaml: |
    # API Server configuration
    host: {{ .Values.apiserver.config.host | quote }}
    port: {{ .Values.apiserver.config.port | quote }}
    batch_ttl_seconds: {{ .Values.apiserver.config.batchTTLSeconds }}
    {{- if .Values.apiserver.config.tenantHeader }}
    tenant_header: {{ .Values.apiserver.config.tenantHeader | quote }}
    {{- end }}
    read_header_timeout_seconds: {{ .Values.apiserver.config.readHeaderTimeoutSeconds }}
    read_timeout_seconds: {{ .Values.apiserver.config.readTimeoutSeconds }}
    write_timeout_seconds: {{ .Values.apiserver.config.writeTimeoutSeconds }}
    idle_timeout_seconds: {{ .Values.apiserver.config.idleTimeoutSeconds }}
    files_api:
      default_expiration_seconds: {{ .Values.apiserver.config.filesAPI.defaultExpirationSeconds }}
      max_size_bytes: {{ .Values.apiserver.config.filesAPI.maxSizeBytes }}
      max_line_count: {{ .Values.apiserver.config.filesAPI.maxLineCount }}
    {{- if .Values.apiserver.tls.enabled }}
    ssl_cert_file: "/etc/tls/tls.crt"
    ssl_key_file: "/etc/tls/tls.key"
    {{- end }}
{{- end }}
